name: Deploy to Firebase Hosting

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: 'live'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLURHASH_DEMO }}'
          projectId: blurhash-demo
